sfdc:
  user: "manjunath.sake1@joinmosaic.com.full"
  pass: "Bhavesh001"
  securityToken: ""
  authenticationURL: "https://test.salesforce.com/services/Soap/u/53.0"
     
       #icdev06 
#sfdc:
#  user: "manjunath.sake@joinmosaic.com.icdev06"
#  pass: "Bhavesh001"
#  securityToken: ""
#  authenticationURL: "https://test.salesforce.com/services/Soap/u/53.0"
     
       
       #E2E
      
#sfdc:
#  user: "mule.integration@joinmosaic.com.e2e"
#  pass: "Mule@123"
#  securityToken: "kOyF4N7e6IFirrIn03DTenk6"
#  authenticationURL: "https://test.salesforce.com/services/Soap/u/53.0"  
kafka:
  bootstrapurl1: "b-1.awskafkanonprod.fvxg41.c3.kafka.us-east-1.amazonaws.com:9094"
  bootstrapurl2: "b-2.awskafkanonprod.fvxg41.c3.kafka.us-east-1.amazonaws.com:9094"
  bootstrapurl3: "b-3.awskafkanonprod.fvxg41.c3.kafka.us-east-1.amazonaws.com:9094"
  groupid: "mulesoft"
  topicname: "event.salesforce.caseupdates.qa"
  eventprocessname : "HVAC-GenericEvent"
flow:
  requesttype: "hvac"

